unbind C-b
set-option -g prefix C-a

set-option -g default-terminal "tmux-256color"
set-option -a terminal-features 'st-256color:RGB'
set-option -a terminal-overrides 'st-256color:Tc'

set-option -g base-index 1
set-option -g focus-events on
set-option -sg escape-time 10
set-option -g mode-keys vi

set-option -g status-position top
set-option -g status-justify absolute-centre
set-option -g status-style "bg=default"
set-option -g status-right ""
set-option -g status-left "#S"

set-option -g window-status-current-style "fg=blue bg=default bold"

bind-key C-a send-prefix
bind-key r source-file ~/.tmux.conf \; display "Reloaded from ~/.tmux.conf"

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key | split-window -h
bind-key - split-window -v

# ✅ Tambahkan ini agar bisa scroll pakai mouse
set -g mouse on
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -selection c"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"
